[project]
name = "debugging-q4"
version = "0.1.0"
description = "CCHC Assessment Debugging Q4"
authors = [{ name = "Timothy Meyer", email = "timmy.meyer416@gmail.com" }]
readme = "README.md"
requires-python = "<=3.11"
dependencies = ["pandas", "numpy"]
